# Версия docker-compose
version: '3'
services:
  app:
    build:
      args:
        user: kim
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: tz
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tz
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - tz
  postgres:
    restart: always
    image: postgres:9.6-alpine
    stop_grace_period: 30s
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      DB_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 127.0.0.88:5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - tz
networks:
  tz:
    driver: bridge
volumes:
  postgresql-data:
    driver: local
